# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hungry Turtle Code
permalink: /:categories/:title/
email: adrian@hungryturtlecode.com
description: Hungry Turtle Code is a site dedicated to teaching developers of all skill levels a bit more about code than they knew yesterday. Whether you are starting from scratch or just looking for that one new tip that will boost your workflow, there is probably something for you here.
# url: "https://hungryturtlecode.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://hungryturtlecode.com"
produrl: "https://hungryturtlecode.com"
baseurl: ""

source: jekyll

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      loop: true

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tags
    category: category
  permalinks:
    tag: '/tag/:name/'
    category: '/:name/'

socialimg: /assets/hungryturtlecode.png
googleplus: u/0/b/102352442157148016670/+Hungryturtledev
twitter_username: hungryturtledev
github_username:  adiman9
github_org: HungryTurtleCode

assets:
  autoprefixer:
    browsers:
      - "last 3 versions"
      - "IE > 9"

image_optim:
  archive_dir: "_image_optim_archive"
  cache_file: "_image_optim_cache.yml"
  image_glob: "jekyll/**/*.{gif,png,jpg,jpeg,svg}"

# Build settings
markdown: kramdown
# markdown: redcarpet
gems:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .scss
  - node_modules
  - package.json
  - webpack.config.js
  - database.rules.bolt
  - firebase.json
  - .asset-cache
include:
  - src/pages
