# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hungry Turtle Code
permalink: /:categories/:title
email: adrian@hungryturtlecode.com
description: > # this means to ignore newlines until "baseurl:"
  Hungry Turtle Code is a site dedicated to teaching developers of all
  skill levels a bit more about code than they knew yesterday. Whether
  you are starting from scratch or just looking for that one new tip that
  will boost your workflow, there is probably something for you here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hungryturtlecode.com" # the base hostname & protocol for your site, e.g. http://example.com

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      loop: true

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tags
    category: category
  permalinks:
    tag: '/tag/:name/'
    category: '/:name/'

default_share_img: /img/social.jpg # Change this image to something actually useful
twitter_username: hungryturtledev
github_username:  adiman9
github_org: HungryTurtleCode

# Build settings
markdown: kramdown
# markdown: redcarpet
gems:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .scss
  - node_modules
  - package.json
  - webpack.config
include:
  - pages
